export const GET_USER = 'GET_USER'
export const SEACRH_USERS = 'SEACRH_USERS'
export const CLEAR_USERS = 'CLEAR_USERS'
export const SET_LOADING = 'SET_LOADING'
export const NOT_LOADING = 'NOT_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'